name: sd3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - torch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - matplotlib=3.9.2
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.2
  - tqdm=4.66.5
  - requests=2.32.3
  - pip
  - pip:
      - diffusers==0.32.0.dev0
      - transformers==4.38.1
      - datasets==2.19.1
      - accelerate==1.1.0
      - peft==0.7.0
      - safetensors==0.4.5
      - sentencepiece==0.2.0
      - torchinfo==1.8.0
      - typing-extensions==4.11.0
